name: Tests

on: [push, pull_request]

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "chiselled_node"
      rock-repo: ${{ github.repository }}
      rock-repo-commit: ${{ github.event_name == 'push' && github.ref_name || github.head_ref }}
      rockfile-directory: node18

  test:
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
    needs: 
      - build
    with:
      oci-archive-name: "chiselled_node"

  notify:
    needs:
      - test
    if: always()
    name: Post workflow status to Mattermost
    runs-on: ubuntu-latest

    steps:
      - name: Create the message
        run: |
          set -eu

          case "${{ needs.test.result }}" in
            failure) msg_icon=":x:" ;;
            success) msg_icon=":white_check_mark:" ;;
            cancelled) msg_icon=":no_entry_sign:" ;;
            *) msg_icon=":grey_question:" ;;
          esac

          msg=$(cat << EOF
          ##### $msg_icon GitHub Workflow '${{ github.workflow	}}' execution [#${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) has ended with the status \`${{ needs.test.result }}\`, for:
           - Project: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})
           - Branch: [${{ github.ref_name }}](${{ github.server_url }}/${{ github.repository }}/tree/${{ github.ref_name }})
           - Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}); _${{ github.event.head_commit.message }}_
           - Triggered by: ${{ github.triggering_actor }}
          EOF
          )

          jq -n --arg message "$msg" >mattermost.json '
            {
              channel_id: "secret",
              message: $message,
            }
          '

      - name: Send the message to Mattermost
        run: |
          cat mattermost.json
