name: Tests

on: [push, pull_request]

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: "chiselled_node"
      rock-repo: ${{ github.event.repository.name }}
      rock-repo-commit: ${{ github.ref_name }}
      rockfile-directory: node18

  test:
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
    needs: [build]
    with:
      oci-archive-name: "chiselled_node"

